# Generated by Django 5.0.2 on 2024-02-22 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prj_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='alluser',
        ),
    ]
